import { FeedItem } from '@/types';
export function genMinimalSnippet(feed: FeedItem): string {
  const escapedTitle = feed.title.replace(/"/g, '&quot;').replace(/'/g, '&apos;');
  return `
<!-- Generated by LV Civic Intelligence Dashboard -->
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap');
  .feed-card-container {
    font-family: 'Inter', sans-serif;
    background-color: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 0.5rem;
    width: 350px;
    overflow: hidden;
    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);
    transition: all 0.2s ease-in-out;
  }
  .feed-card-container:hover {
    box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
    transform: translateY(-2px);
  }
  .card-header { padding: 1rem; }
  .card-title { font-size: 1rem; font-weight: 600; color: #1e293b; }
  .card-badge {
    display: inline-block;
    margin-top: 0.5rem;
    padding: 0.25rem 0.75rem;
    font-size: 0.75rem;
    font-weight: 500;
    border-radius: 9999px;
    background-color: #f1f5f9;
    color: #475569;
  }
  .card-footer {
    padding: 0.5rem 1rem;
    border-top: 1px solid #e2e8f0;
    display: flex;
    justify-content: flex-end;
  }
  .card-button {
    font-size: 0.875rem;
    padding: 0.5rem 1rem;
    border-radius: 0.375rem;
    background-color: #4f46e5;
    color: white;
    text-decoration: none;
  }
</style>
<div class="feed-card-container">
  <div class="card-header">
    <h3 class="card-title">${escapedTitle}</h3>
    <div class="card-badge">${feed.category}</div>
  </div>
  <div class="card-footer">
    <a href="${feed.url}" target="_blank" rel="noopener noreferrer" class="card-button">Subscribe</a>
  </div>
</div>
<script>
  // No JS needed for this basic component.
</script>
`;
}